"""assessment_columns

Revision ID: 0ac8107d675a
Revises: e02c7d9d0404
Create Date: 2023-11-17 20:02:48.380278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac8107d675a'
down_revision: Union[str, None] = 'e02c7d9d0404'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicant_jobs', sa.Column('resume', sa.Boolean(), default=False))
    op.add_column('applicant_jobs', sa.Column('job_fit', sa.Boolean(), default=False))
    op.add_column('applicant_jobs', sa.Column('aptitude', sa.Boolean(), default=False))
    op.add_column('applicant_jobs', sa.Column('skill', sa.Boolean(), default=False))    
    op.add_column('applicant_jobs', sa.Column('completed', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_column('applicant_jobs', 'skill')
    op.drop_column('applicant_jobs', 'aptitude')
    op.drop_column('applicant_jobs', 'job_fit')
    op.drop_column('applicant_jobs', 'resume')
    # ### end Alembic commands ###
