"""save_difficulty_in_table

Revision ID: 17a24d61b06a
Revises: 0ac8107d675a
Create Date: 2023-11-18 12:50:03.382896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17a24d61b06a'
down_revision: Union[str, None] = '0ac8107d675a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###        
    # op.add_column('jobs', sa.Column('aptitude_difficulty', sa.Enum('easy', 'medium', 'hard', 'mix'), nullable=True))
    # op.add_column('jobs', sa.Column('skill_difficulty', sa.Enum('easy', 'medium', 'hard', 'mix'), nullable=True))    
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('applicants_id', 'skills', ['applicant_id'], unique=False)
    op.drop_column('jobs', 'skill_difficulty')
    op.drop_column('jobs', 'aptitude_difficulty')
    op.create_index('applicants_id', 'experience', ['applicant_id'], unique=False)
    op.create_index('applicants_id', 'education', ['applicant_id'], unique=False)
    op.drop_column('applicant_jobs', 'completed')
    op.drop_column('applicant_jobs', 'skill')
    op.drop_column('applicant_jobs', 'aptitude')
    op.drop_column('applicant_jobs', 'job_fit')
    op.drop_column('applicant_jobs', 'resume')
    # ### end Alembic commands ###
