"""changed_columns_in_report

Revision ID: ac554b0e746d
Revises: c129b5d07f8c
Create Date: 2023-11-19 13:48:23.928333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ac554b0e746d'
down_revision: Union[str, None] = 'c129b5d07f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('aptitude_score', sa.Integer(), nullable=True))
    op.alter_column('reports', 'job_fit_score',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.drop_column('reports', 'resume_score')    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###    
    op.add_column('reports', sa.Column('resume_score', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('reports', 'job_fit_score',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_column('reports', 'aptitude_score')
    # ### end Alembic commands ###
