"""change_columns_in_reports_table

Revision ID: c129b5d07f8c
Revises: 338e46e04909
Create Date: 2023-11-19 13:28:17.399340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c129b5d07f8c'
down_revision: Union[str, None] = '338e46e04909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###    
    op.add_column('reports', sa.Column('job_fit_score', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('resume_score', sa.Integer(), nullable=True))
    op.add_column('reports', sa.Column('skill_score', sa.Integer(), nullable=True))
    op.drop_column('reports', 'experience')
    op.drop_column('reports', 'projects')
    op.drop_column('reports', 'achievements')
    op.drop_column('reports', 'coding_profiles')
    op.drop_column('reports', 'skills')
    op.drop_column('reports', 'education')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('applicants_id', 'skills', ['applicant_id'], unique=False)
    op.add_column('reports', sa.Column('education', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('skills', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('coding_profiles', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('achievements', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('projects', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('reports', sa.Column('experience', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('reports', 'skill_score')
    op.drop_column('reports', 'resume_score')
    op.drop_column('reports', 'job_fit_score')
    op.create_index('applicants_id', 'experience', ['applicant_id'], unique=False)
    op.create_index('applicants_id', 'education', ['applicant_id'], unique=False)
    # ### end Alembic commands ###
