"""add_resume_column_applicants_table

Revision ID: f6acf492a61e
Revises: cb6e76329ee9
Create Date: 2023-11-19 12:33:44.178039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6acf492a61e'
down_revision: Union[str, None] = 'cb6e76329ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applicants', sa.Column('resume', sa.Boolean(), nullable=True))    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('applicants_id', 'skills', ['applicant_id'], unique=False)
    op.create_index('applicants_id', 'experience', ['applicant_id'], unique=False)
    op.create_index('applicants_id', 'education', ['applicant_id'], unique=False)
    op.drop_column('applicants', 'resume')
    # ### end Alembic commands ###
