"""add_column_in_jobs

Revision ID: feda94300ee8
Revises: 8be839176794
Create Date: 2023-11-21 01:12:48.264845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feda94300ee8'
down_revision: Union[str, None] = '8be839176794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('is_job_fit', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('is_aptitude', sa.Boolean(), nullable=True))
    op.add_column('jobs', sa.Column('is_skill', sa.Boolean(), nullable=True))    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###    
    op.drop_column('jobs', 'is_skill')
    op.drop_column('jobs', 'is_aptitude')
    op.drop_column('jobs', 'is_job_fit')
    # ### end Alembic commands ###
